In [32]:
import pandas as pd
import numpy as np

In [34]:
data=pd.read_csv("naivebayes_ml.csv")

In [36]:
data.head()

   Height  Weight  Age  CGPA  Gender
0     165      55   20   6.5  Female
1     170      68   21   7.2    Male
2     160      50   19   6.0  Female
3     175      72   22   7.8    Male
4     168      58   20   6.9  Female

In [38]:
data.tail()

    Height  Weight  Age  CGPA  Gender
25     182      84   24   8.4    Male
26     160      51   19   6.0  Female
27     175      73   22   7.6    Male
28     168      59   20   6.9  Female
29     178      77   23   8.1    Male

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Height  30 non-null     int64
 1   Weight  30 non-null     int64
 2   Age     30 non-null     int64
 3   CGPA    30 non-null     float64
 4   Gender  30 non-null     object
dtypes: float64(1), int64(3), object(1)
memory usage: 1.3+ KB

In [42]:
data.describe()

           Height     Weight        Age       CGPA
count   30.000000  30.000000  30.000000  30.000000
mean   169.466667  63.766667  20.666667   7.033333
std      7.605503  11.663924   1.667816   0.824761
min    157.000000  47.000000  18.000000   5.700000
25%    163.250000  53.250000  19.250000   6.325000
50%    169.000000  63.000000  20.500000   7.000000
75%    175.750000  73.750000  22.000000   7.775000
max    182.000000  84.000000  24.000000   8.400000

In [44]:
data.shape

(30, 5)

In [46]:
data.columns

Index(['Height', 'Weight', 'Age', 'CGPA', 'Gender'], dtype='object')

In [ ]:
#-----Gaussian Naive -----------#

In [ ]:
Gaussian Naïve Bayes
Used for numerical data.
Calculates Mean and Variance.
Finds probability for each class.
Compares probabilities.
Chooses the highest probability.
Gives prediction.

Example: Height, Weight, Age

In [50]:
from sklearn.naive_bayes import GaussianNB

X = data[["Height","Weight","Age","CGPA"]]
y = data["Gender"]

model = GaussianNB()
model.fit(X,y)

new_data = pd.DataFrame({
    "Height":[172],
    "Weight":[65],
    "Age":[21],
    "CGPA":[7.5]
})

result = model.predict(new_data)

print(result)

['Male']

In [ ]:
#------------------multinomial naive-------------------------#

In [ ]:
Multinomial Naïve Bayes
Used for count/frequency data.
Counts feature occurrences.
Calculates probability for each class.
Compares probabilities.
Chooses the highest probability.
Gives prediction.

Example: Word counts in emails

In [58]:
from sklearn.naive_bayes import MultinomialNB
data1=pd.read_csv("multinomial.csv")

X = data1[["Free_Count",
          "Win_Count",
          "Offer_Count",
          "Prize_Count",
          "Click_Count"]]

y = data1["Class"]
model = MultinomialNB()
model.fit(X, y)
new_data = pd.DataFrame({
    "Free_Count":[4],
    "Win_Count":[2],
    "Offer_Count":[1],
    "Prize_Count":[1],
    "Click_Count":[3]
})

result = model.predict(new_data)

print("Prediction:", result)

Prediction: ['Spam']

In [ ]:
#--------bernoulli  naive----------------------------------#

In [ ]:
Bernoulli Naïve Bayes - Very Simple Points
Uses 0 and 1 data.
Works with Yes/No values.
Learns from training data.
Uses Bayes Theorem.
Calculates probability.
Compares all classes.
Chooses the highest probability.
Gives the prediction.

In [60]:
from sklearn.naive_bayes import BernoulliNB

data = pd.read_csv("bernoulli.csv")
X = data[["Fever", "Cough", "Headache"]]
y = data["Disease"]
model = BernoulliNB()
model.fit(X, y)

new_data = pd.DataFrame({
    "Fever": [1],
    "Cough": [1],
    "Headache": [0]
})
result = model.predict(new_data)

print("Prediction:", result)

Prediction: ['Yes']